### ISSUE TITLE
Trivy update breaks container image scanning

### ISSUE THREAD

**Issue by wjdingman1** [broadinstitute/dsp-appsec-trivy-action#8]
Previously you were able to scan container images without specifying the `image` command:

`aquaseq/trivy --vuln-type os --severity CRITICAL python:3.7`

Trivy has updated to `0.23.0` which requires the command change:

`aquaseq/trivy image --vuln-type os --severity CRITICAL python:3.7`

**Comment by dinvlad** [comment]
thx, addressed in https://github.com/broadinstitute/dsp-appsec-trivy-action/pull/9
